"""init

Revision ID: 262d3173454c
Revises: 
Create Date: 2023-05-11 16:38:16.897619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262d3173454c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.Enum('cat', 'dog', 'parrot', name='typeenum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sexenum'), nullable=True),
    sa.Column('breed', sa.Enum('husky', 'shepherd', 'mongrel', name='breedenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=254), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sexenum'), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('clients_pets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'pet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients_pets')
    op.drop_table('users')
    op.drop_table('pets')
    # ### end Alembic commands ###
